<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rung.Drivers.Fins\Rung.Drivers.Fins.csproj" />
    <ProjectReference Include="..\..\src\Rung.Simulator\Rung.Simulator.csproj" />
  </ItemGroup>
</Project>
