<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FluentModbus" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rung.Drivers.Modbus\Rung.Drivers.Modbus.csproj" />
  </ItemGroup>
</Project>
