/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 网关整体健康状况
         * @description 有设备掉线时 status 为 degraded。适合直接接监控探针。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部设备的运行状况 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单台设备的运行状况 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceView"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 点位最新值
         * @description 可用 device 与 prefix 过滤。prefix 按业务名前缀匹配。
         */
        get: {
            parameters: {
                query?: {
                    device?: string;
                    prefix?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tagName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单个点位的最新值 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagView"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tagName}/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 写入点位
         * @description 值按点位声明的数据类型解释。写完会记审计日志，并回读设备上的真实值。 路径上显式写出 write 而不是用 PUT：这个动作会让产线上的机器真的动起来， 一眼看得出比符合 REST 惯例更重要。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagName: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WriteTagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 点位变化的实时推送（SSE）
         * @description 只推送越过死区的变化。浏览器用 EventSource 订阅，自带断线重连。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SseItemOfTagView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 从配置源重新加载
         * @description 只有配置真的变了的设备会被重启，其余原地继续跑，采集不中断。 校验失败时配置原封不动，不会留下一个改了一半的网关。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReloadView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 最近的写操作审计
         * @description 谁、什么时候、往哪个点位写了什么值，以及设备回读到的实际值。 失败的尝试同样留痕。
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WriteAuditRecord"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前配置摘要 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigSummaryView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 导出点位表为 Excel
         * @description 导出的文件改完可以直接上传回来。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 只校验上传的配置，不写入
         * @description 上传 .xlsx 或 .json，逐行报出问题。不改变任何现有配置。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigCheckView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导入配置并立即生效
         * @description 上传 .xlsx 或 .json。先校验，有问题就整份拒绝；通过之后写入并在线重载，只有配置真的变了的设备会被重启。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 整份配置的校验结果。 */
        ConfigCheckView: {
            /** @description 逐设备结果。 */
            devices: components["schemas"]["DeviceCheckView"][];
            /** @description 跨设备重复的点位名。 */
            duplicateTagNames: string[];
            /** @description 解析文件时逐行发现的问题（仅 Excel）。 */
            fileIssues: string[];
            /**
             * Format: int32
             * @description 点位总数。
             */
            tagCount: number;
            /**
             * Format: int32
             * @description 每轮请求总数。
             */
            requestCount: number;
            /**
             * Format: int32
             * @description 问题总数。
             */
            problemCount: number;
        };
        /** @description 配置来源摘要。 */
        ConfigSummaryView: {
            /** @description 来源描述。 */
            source: string;
            /** @description 是否可在线修改。JSON 文件来源为只读。 */
            writable: boolean;
            /**
             * Format: int32
             * @description 设备数。
             */
            deviceCount: number;
            /**
             * Format: int32
             * @description 点位数。
             */
            tagCount: number;
        };
        /** @description 一台设备的校验结果。 */
        DeviceCheckView: {
            /** @description 设备标识。 */
            deviceId: string;
            /** @description 协议。 */
            protocol: string;
            /**
             * Format: int32
             * @description 点位数。
             */
            tagCount: number;
            /**
             * Format: int32
             * @description 每轮请求次数。
             */
            requestCount: number;
            /** @description 配置问题。 */
            issues: components["schemas"]["TagIssueView"][];
        };
        /** @description 一台设备的对外状况。 */
        DeviceView: {
            /** @description 设备标识。 */
            deviceId: string;
            /** @description 连接状态。 */
            state: string;
            /**
             * Format: date-time
             * @description 最近一次成功采集时刻。
             */
            lastSuccessUtc: null | string;
            /**
             * Format: date-time
             * @description 最近一次失败时刻。
             */
            lastFailureUtc: null | string;
            /** @description 最近一次错误描述。 */
            lastError: null | string;
            /**
             * Format: int32
             * @description 连续失败次数。
             */
            consecutiveFailures: number;
            /**
             * Format: int32
             * @description 累计重连次数。
             */
            reconnectCount: number;
            /**
             * Format: double
             * @description 上一轮采集耗时，毫秒。
             */
            lastPollMs: number;
            /**
             * Format: int32
             * @description 单次报文的最大字节数。S7 是协商出来的，其余协议是写死的上限。
             */
            maxFrameBytes: number;
            /**
             * Format: int32
             * @description 参与采集的点位数。
             */
            activeTagCount: number;
            /**
             * Format: int32
             * @description 每轮请求次数。
             */
            requestCount: number;
            /**
             * Format: int32
             * @description 采集超时次数。
             */
            overrunCount: number;
            /** @description 配置有问题的点位。 */
            issues: components["schemas"]["TagIssueView"][];
        };
        /** @description 网关整体健康状况。 */
        HealthView: {
            /** @description healthy / degraded。有设备掉线即为 degraded。 */
            status: string;
            /**
             * Format: int32
             * @description 设备总数。
             */
            deviceCount: number;
            /**
             * Format: int32
             * @description 已连接的设备数。
             */
            connectedCount: number;
            /**
             * Format: int32
             * @description 缓存中的点位数。
             */
            tagCount: number;
            /**
             * Format: int32
             * @description 配置有问题的点位总数。
             */
            issueCount: number;
            /**
             * Format: double
             * @description 运行时长，秒。
             */
            uptimeSeconds: number;
        };
        /** Format: binary */
        IFormFile: string;
        /** @description 导入并生效的结果。 */
        ImportView: {
            /** @description 导入的设备校验结果。 */
            devices: components["schemas"]["DeviceCheckView"][];
            /** @description 新启动的设备。 */
            added: string[];
            /** @description 被重启的设备。 */
            restarted: string[];
            /** @description 被移除的设备。 */
            removed: string[];
            /** @description 原地继续跑的设备。 */
            unchanged: string[];
        };
        JsonElement: unknown;
        /** @description 一次配置重载的结果。 */
        ReloadView: {
            /** @description 配置来源描述。 */
            source: string;
            /** @description 新启动的设备。 */
            added: string[];
            /** @description 配置变了、被重启的设备。 */
            restarted: string[];
            /** @description 被移除的设备。 */
            removed: string[];
            /** @description 配置未变、原地继续跑的设备。 */
            unchanged: string[];
        };
        SseItemOfTagView: {
            data?: components["schemas"]["TagView"];
            eventType?: null | string;
            eventId?: null | string;
            reconnectionInterval?: null | string;
        };
        /** @description 一个点位的配置问题。 */
        TagIssueView: {
            /** @description 点位名。 */
            tagName: string;
            /** @description 原因，应当足以让电气工程师自己改对。 */
            reason: string;
        };
        /**
         * @description 一个点位的对外表示。
         *         刻意不暴露 TagValue 本身：它是为热路径设计的紧凑结构体，
         *     换成 JSON 友好的形状之后，接口契约才能独立于内部实现演进。
         */
        TagView: {
            /** @description 业务点位名。 */
            name: string;
            /** @description 当前值。质量不佳时为 null。 */
            value: unknown;
            /** @description 采集质量。 */
            quality: string;
            /**
             * Format: date-time
             * @description 采集时刻，UTC。
             */
            timestampUtc: string;
            /** @description 来源设备。 */
            deviceId: string;
            /** @description 协议地址，便于现场核对。 */
            address: string;
            /** @description 数据类型。 */
            dataType: string;
            /** @description 描述。 */
            description: null | string;
        };
        /** @description 一条写操作的审计记录。 */
        WriteAuditRecord: {
            /**
             * Format: date-time
             * @description 操作时刻，UTC。
             */
            timestampUtc: string;
            /** @description 调用方名称，来自 API 密钥。 */
            caller: string;
            /** @description 设备标识。 */
            deviceId: string;
            /** @description 业务点位名。 */
            tagName: string;
            /** @description 协议地址。排障时手头只有审计文件也能直接看懂。 */
            address: string;
            /**
             * @description 数据类型。拆成独立字段而不是拼进值里——
             *                 选 JSON Lines 就是为了机器也能解析，让消费方去拆 "266 [Float64]" 这种复合串
             *                 是把方便留给自己、麻烦留给别人。
             */
            dataType: string;
            /** @description 请求写入的工程值。 */
            requested: string;
            /** @description 写完从设备回读到的实际值；失败时为空。 */
            actual: null | string;
            /** @description 是否成功。 */
            success: boolean;
            /** @description 失败原因。 */
            error: null | string;
        };
        /** @description 写点位的请求体。 */
        WriteTagRequest: {
            /** @description 要写入的工程值。网关按点位的数据类型自行转换。 */
            value: components["schemas"]["JsonElement"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
