/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 网关整体健康状况
         * @description 有设备掉线时 status 为 degraded。适合直接接监控探针。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部设备的运行状况 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单台设备的运行状况 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceView"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 点位最新值
         * @description 可用 device 与 prefix 过滤。prefix 按业务名前缀匹配。
         */
        get: {
            parameters: {
                query?: {
                    device?: string;
                    prefix?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tagName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单个点位的最新值 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagView"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tagName}/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 写入点位
         * @description 值按点位声明的数据类型解释。写完会记审计日志，并回读设备上的真实值。 路径上显式写出 write 而不是用 PUT：这个动作会让产线上的机器真的动起来， 一眼看得出比符合 REST 惯例更重要。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagName: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WriteTagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 点位变化的实时推送（SSE）
         * @description 只推送越过死区的变化。浏览器用 EventSource 订阅，自带断线重连。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SseItemOfTagView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 一台设备的对外状况。 */
        DeviceView: {
            /** @description 设备标识。 */
            deviceId: string;
            /** @description 连接状态。 */
            state: string;
            /**
             * Format: date-time
             * @description 最近一次成功采集时刻。
             */
            lastSuccessUtc: null | string;
            /**
             * Format: date-time
             * @description 最近一次失败时刻。
             */
            lastFailureUtc: null | string;
            /** @description 最近一次错误描述。 */
            lastError: null | string;
            /**
             * Format: int32
             * @description 连续失败次数。
             */
            consecutiveFailures: number;
            /**
             * Format: int32
             * @description 累计重连次数。
             */
            reconnectCount: number;
            /**
             * Format: double
             * @description 上一轮采集耗时，毫秒。
             */
            lastPollMs: number;
            /**
             * Format: int32
             * @description 协商的 PDU 长度。
             */
            negotiatedPduLength: number;
            /**
             * Format: int32
             * @description 参与采集的点位数。
             */
            activeTagCount: number;
            /**
             * Format: int32
             * @description 每轮请求次数。
             */
            requestCount: number;
            /**
             * Format: int32
             * @description 采集超时次数。
             */
            overrunCount: number;
            /** @description 配置有问题的点位。 */
            issues: components["schemas"]["TagIssueView"][];
        };
        /** @description 网关整体健康状况。 */
        HealthView: {
            /** @description healthy / degraded。有设备掉线即为 degraded。 */
            status: string;
            /**
             * Format: int32
             * @description 设备总数。
             */
            deviceCount: number;
            /**
             * Format: int32
             * @description 已连接的设备数。
             */
            connectedCount: number;
            /**
             * Format: int32
             * @description 缓存中的点位数。
             */
            tagCount: number;
            /**
             * Format: int32
             * @description 配置有问题的点位总数。
             */
            issueCount: number;
            /**
             * Format: double
             * @description 运行时长，秒。
             */
            uptimeSeconds: number;
        };
        JsonElement: unknown;
        SseItemOfTagView: {
            data?: components["schemas"]["TagView"];
            eventType?: null | string;
            eventId?: null | string;
            reconnectionInterval?: null | string;
        };
        /** @description 一个点位的配置问题。 */
        TagIssueView: {
            /** @description 点位名。 */
            tagName: string;
            /** @description 原因，应当足以让电气工程师自己改对。 */
            reason: string;
        };
        /**
         * @description 一个点位的对外表示。
         *         刻意不暴露 TagValue 本身：它是为热路径设计的紧凑结构体，
         *     换成 JSON 友好的形状之后，接口契约才能独立于内部实现演进。
         */
        TagView: {
            /** @description 业务点位名。 */
            name: string;
            /** @description 当前值。质量不佳时为 null。 */
            value: unknown;
            /** @description 采集质量。 */
            quality: string;
            /**
             * Format: date-time
             * @description 采集时刻，UTC。
             */
            timestampUtc: string;
            /** @description 来源设备。 */
            deviceId: string;
            /** @description 协议地址，便于现场核对。 */
            address: string;
            /** @description 数据类型。 */
            dataType: string;
            /** @description 描述。 */
            description: null | string;
        };
        /** @description 写点位的请求体。 */
        WriteTagRequest: {
            /** @description 要写入的工程值。网关按点位的数据类型自行转换。 */
            value: components["schemas"]["JsonElement"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
