<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="MQTTnet.Server" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rung.Sinks.Mqtt\Rung.Sinks.Mqtt.csproj" />
  </ItemGroup>
</Project>
